// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ecotone/v1/normalization.proto

package ecotone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to normalize an utterance.
type NormalizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw input text (e.g. "The train left at 3:30 carrying $40.25").
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Language code (e.g. "en", "es", "de"). Default is "en".
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// If true, populates token_links with character alignment and token metadata.
	ShowTokenLinks bool `protobuf:"varint,3,opt,name=show_token_links,json=showTokenLinks,proto3" json:"show_token_links,omitempty"`
	// If true, splits the text into sentences first and normalizes each sentence.
	SplitSentences bool `protobuf:"varint,4,opt,name=split_sentences,json=splitSentences,proto3" json:"split_sentences,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NormalizeRequest) Reset() {
	*x = NormalizeRequest{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeRequest) ProtoMessage() {}

func (x *NormalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeRequest.ProtoReflect.Descriptor instead.
func (*NormalizeRequest) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NormalizeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NormalizeRequest) GetShowTokenLinks() bool {
	if x != nil {
		return x.ShowTokenLinks
	}
	return false
}

func (x *NormalizeRequest) GetSplitSentences() bool {
	if x != nil {
		return x.SplitSentences
	}
	return false
}

// Response containing normalized text.
type NormalizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The normalized, linearized string of spoken words.
	NormalizedText string `protobuf:"bytes,1,opt,name=normalized_text,json=normalizedText,proto3" json:"normalized_text,omitempty"`
	// Detailed token-to-word links and character offsets if requested.
	TokenLinks string `protobuf:"bytes,2,opt,name=token_links,json=tokenLinks,proto3" json:"token_links,omitempty"`
	// List of normalized individual sentences (if split_sentences was requested).
	Sentences []string `protobuf:"bytes,3,rep,name=sentences,proto3" json:"sentences,omitempty"`
	// Server-side processing time in milliseconds.
	LatencyMs     float32 `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeResponse) Reset() {
	*x = NormalizeResponse{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeResponse) ProtoMessage() {}

func (x *NormalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeResponse.ProtoReflect.Descriptor instead.
func (*NormalizeResponse) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizeResponse) GetNormalizedText() string {
	if x != nil {
		return x.NormalizedText
	}
	return ""
}

func (x *NormalizeResponse) GetTokenLinks() string {
	if x != nil {
		return x.TokenLinks
	}
	return ""
}

func (x *NormalizeResponse) GetSentences() []string {
	if x != nil {
		return x.Sentences
	}
	return nil
}

func (x *NormalizeResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// Request to normalize a batch of utterances.
type NormalizeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NormalizeRequest    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeBatchRequest) Reset() {
	*x = NormalizeBatchRequest{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeBatchRequest) ProtoMessage() {}

func (x *NormalizeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeBatchRequest.ProtoReflect.Descriptor instead.
func (*NormalizeBatchRequest) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{2}
}

func (x *NormalizeBatchRequest) GetItems() []*NormalizeRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

// Response for a batch normalization request.
type NormalizeBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*NormalizeResponse   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Total server-side batch duration in milliseconds.
	TotalLatencyMs float32 `protobuf:"fixed32,2,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NormalizeBatchResponse) Reset() {
	*x = NormalizeBatchResponse{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeBatchResponse) ProtoMessage() {}

func (x *NormalizeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeBatchResponse.ProtoReflect.Descriptor instead.
func (*NormalizeBatchResponse) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{3}
}

func (x *NormalizeBatchResponse) GetItems() []*NormalizeResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *NormalizeBatchResponse) GetTotalLatencyMs() float32 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

// Request to split text into sentences.
type SplitSentencesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input document or multi-line text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Language code. Default is "en".
	Language      string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitSentencesRequest) Reset() {
	*x = SplitSentencesRequest{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitSentencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitSentencesRequest) ProtoMessage() {}

func (x *SplitSentencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitSentencesRequest.ProtoReflect.Descriptor instead.
func (*SplitSentencesRequest) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{4}
}

func (x *SplitSentencesRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SplitSentencesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Response containing split sentences.
type SplitSentencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sentences     []string               `protobuf:"bytes,1,rep,name=sentences,proto3" json:"sentences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitSentencesResponse) Reset() {
	*x = SplitSentencesResponse{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitSentencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitSentencesResponse) ProtoMessage() {}

func (x *SplitSentencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitSentencesResponse.ProtoReflect.Descriptor instead.
func (*SplitSentencesResponse) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{5}
}

func (x *SplitSentencesResponse) GetSentences() []string {
	if x != nil {
		return x.Sentences
	}
	return nil
}

// Request to hot-reload normalizer grammars.
type ReloadGrammarsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path prefix for grammar files (e.g., "data/"). If omitted, keeps current.
	PathPrefix string `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Name of configuration ASCII proto (e.g. "sparrowhawk_configuration.ascii_proto"). If omitted, keeps current.
	ConfigFile string `protobuf:"bytes,2,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	// Number of worker instances in pool. If omitted or 0, keeps current pool size.
	Workers uint32 `protobuf:"varint,3,opt,name=workers,proto3" json:"workers,omitempty"`
	// Specific ISO language code to reload or add (e.g. "es", "de", "en").
	// If omitted or empty, reloads the default active language or active configurations.
	Language      string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadGrammarsRequest) Reset() {
	*x = ReloadGrammarsRequest{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadGrammarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadGrammarsRequest) ProtoMessage() {}

func (x *ReloadGrammarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadGrammarsRequest.ProtoReflect.Descriptor instead.
func (*ReloadGrammarsRequest) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadGrammarsRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *ReloadGrammarsRequest) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *ReloadGrammarsRequest) GetWorkers() uint32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *ReloadGrammarsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Response from hot-reloading grammars.
type ReloadGrammarsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if reload succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Descriptive message or error details.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Time taken to load grammars in milliseconds.
	ReloadLatencyMs float32 `protobuf:"fixed32,3,opt,name=reload_latency_ms,json=reloadLatencyMs,proto3" json:"reload_latency_ms,omitempty"`
	// Active configuration file currently serving.
	ActiveConfig string `protobuf:"bytes,4,opt,name=active_config,json=activeConfig,proto3" json:"active_config,omitempty"`
	// Active path prefix currently serving.
	ActivePathPrefix string `protobuf:"bytes,5,opt,name=active_path_prefix,json=activePathPrefix,proto3" json:"active_path_prefix,omitempty"`
	// Active number of worker instances in pool.
	ActiveWorkers uint32 `protobuf:"varint,6,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	// All active languages currently loaded in memory.
	ActiveLanguages []string `protobuf:"bytes,7,rep,name=active_languages,json=activeLanguages,proto3" json:"active_languages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReloadGrammarsResponse) Reset() {
	*x = ReloadGrammarsResponse{}
	mi := &file_ecotone_v1_normalization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadGrammarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadGrammarsResponse) ProtoMessage() {}

func (x *ReloadGrammarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecotone_v1_normalization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadGrammarsResponse.ProtoReflect.Descriptor instead.
func (*ReloadGrammarsResponse) Descriptor() ([]byte, []int) {
	return file_ecotone_v1_normalization_proto_rawDescGZIP(), []int{7}
}

func (x *ReloadGrammarsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadGrammarsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadGrammarsResponse) GetReloadLatencyMs() float32 {
	if x != nil {
		return x.ReloadLatencyMs
	}
	return 0
}

func (x *ReloadGrammarsResponse) GetActiveConfig() string {
	if x != nil {
		return x.ActiveConfig
	}
	return ""
}

func (x *ReloadGrammarsResponse) GetActivePathPrefix() string {
	if x != nil {
		return x.ActivePathPrefix
	}
	return ""
}

func (x *ReloadGrammarsResponse) GetActiveWorkers() uint32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *ReloadGrammarsResponse) GetActiveLanguages() []string {
	if x != nil {
		return x.ActiveLanguages
	}
	return nil
}

var File_ecotone_v1_normalization_proto protoreflect.FileDescriptor

const file_ecotone_v1_normalization_proto_rawDesc = "" +
	"\n" +
	"\x1eecotone/v1/normalization.proto\x12\n" +
	"ecotone.v1\"\x95\x01\n" +
	"\x10NormalizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12(\n" +
	"\x10show_token_links\x18\x03 \x01(\bR\x0eshowTokenLinks\x12'\n" +
	"\x0fsplit_sentences\x18\x04 \x01(\bR\x0esplitSentences\"\x9a\x01\n" +
	"\x11NormalizeResponse\x12'\n" +
	"\x0fnormalized_text\x18\x01 \x01(\tR\x0enormalizedText\x12\x1f\n" +
	"\vtoken_links\x18\x02 \x01(\tR\n" +
	"tokenLinks\x12\x1c\n" +
	"\tsentences\x18\x03 \x03(\tR\tsentences\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\"K\n" +
	"\x15NormalizeBatchRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.ecotone.v1.NormalizeRequestR\x05items\"w\n" +
	"\x16NormalizeBatchResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.ecotone.v1.NormalizeResponseR\x05items\x12(\n" +
	"\x10total_latency_ms\x18\x02 \x01(\x02R\x0etotalLatencyMs\"G\n" +
	"\x15SplitSentencesRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"6\n" +
	"\x16SplitSentencesResponse\x12\x1c\n" +
	"\tsentences\x18\x01 \x03(\tR\tsentences\"\x8f\x01\n" +
	"\x15ReloadGrammarsRequest\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x1f\n" +
	"\vconfig_file\x18\x02 \x01(\tR\n" +
	"configFile\x12\x18\n" +
	"\aworkers\x18\x03 \x01(\rR\aworkers\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\x9d\x02\n" +
	"\x16ReloadGrammarsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11reload_latency_ms\x18\x03 \x01(\x02R\x0freloadLatencyMs\x12#\n" +
	"\ractive_config\x18\x04 \x01(\tR\factiveConfig\x12,\n" +
	"\x12active_path_prefix\x18\x05 \x01(\tR\x10activePathPrefix\x12%\n" +
	"\x0eactive_workers\x18\x06 \x01(\rR\ractiveWorkers\x12)\n" +
	"\x10active_languages\x18\a \x03(\tR\x0factiveLanguages2\xeb\x02\n" +
	"\x14NormalizationService\x12H\n" +
	"\tNormalize\x12\x1c.ecotone.v1.NormalizeRequest\x1a\x1d.ecotone.v1.NormalizeResponse\x12W\n" +
	"\x0eNormalizeBatch\x12!.ecotone.v1.NormalizeBatchRequest\x1a\".ecotone.v1.NormalizeBatchResponse\x12W\n" +
	"\x0eSplitSentences\x12!.ecotone.v1.SplitSentencesRequest\x1a\".ecotone.v1.SplitSentencesResponse\x12W\n" +
	"\x0eReloadGrammars\x12!.ecotone.v1.ReloadGrammarsRequest\x1a\".ecotone.v1.ReloadGrammarsResponseB9Z7github.com/ghchinoy/ecotone/gen/go/ecotone/v1;ecotonev1b\x06proto3"

var (
	file_ecotone_v1_normalization_proto_rawDescOnce sync.Once
	file_ecotone_v1_normalization_proto_rawDescData []byte
)

func file_ecotone_v1_normalization_proto_rawDescGZIP() []byte {
	file_ecotone_v1_normalization_proto_rawDescOnce.Do(func() {
		file_ecotone_v1_normalization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ecotone_v1_normalization_proto_rawDesc), len(file_ecotone_v1_normalization_proto_rawDesc)))
	})
	return file_ecotone_v1_normalization_proto_rawDescData
}

var file_ecotone_v1_normalization_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ecotone_v1_normalization_proto_goTypes = []any{
	(*NormalizeRequest)(nil),       // 0: ecotone.v1.NormalizeRequest
	(*NormalizeResponse)(nil),      // 1: ecotone.v1.NormalizeResponse
	(*NormalizeBatchRequest)(nil),  // 2: ecotone.v1.NormalizeBatchRequest
	(*NormalizeBatchResponse)(nil), // 3: ecotone.v1.NormalizeBatchResponse
	(*SplitSentencesRequest)(nil),  // 4: ecotone.v1.SplitSentencesRequest
	(*SplitSentencesResponse)(nil), // 5: ecotone.v1.SplitSentencesResponse
	(*ReloadGrammarsRequest)(nil),  // 6: ecotone.v1.ReloadGrammarsRequest
	(*ReloadGrammarsResponse)(nil), // 7: ecotone.v1.ReloadGrammarsResponse
}
var file_ecotone_v1_normalization_proto_depIdxs = []int32{
	0, // 0: ecotone.v1.NormalizeBatchRequest.items:type_name -> ecotone.v1.NormalizeRequest
	1, // 1: ecotone.v1.NormalizeBatchResponse.items:type_name -> ecotone.v1.NormalizeResponse
	0, // 2: ecotone.v1.NormalizationService.Normalize:input_type -> ecotone.v1.NormalizeRequest
	2, // 3: ecotone.v1.NormalizationService.NormalizeBatch:input_type -> ecotone.v1.NormalizeBatchRequest
	4, // 4: ecotone.v1.NormalizationService.SplitSentences:input_type -> ecotone.v1.SplitSentencesRequest
	6, // 5: ecotone.v1.NormalizationService.ReloadGrammars:input_type -> ecotone.v1.ReloadGrammarsRequest
	1, // 6: ecotone.v1.NormalizationService.Normalize:output_type -> ecotone.v1.NormalizeResponse
	3, // 7: ecotone.v1.NormalizationService.NormalizeBatch:output_type -> ecotone.v1.NormalizeBatchResponse
	5, // 8: ecotone.v1.NormalizationService.SplitSentences:output_type -> ecotone.v1.SplitSentencesResponse
	7, // 9: ecotone.v1.NormalizationService.ReloadGrammars:output_type -> ecotone.v1.ReloadGrammarsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ecotone_v1_normalization_proto_init() }
func file_ecotone_v1_normalization_proto_init() {
	if File_ecotone_v1_normalization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ecotone_v1_normalization_proto_rawDesc), len(file_ecotone_v1_normalization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecotone_v1_normalization_proto_goTypes,
		DependencyIndexes: file_ecotone_v1_normalization_proto_depIdxs,
		MessageInfos:      file_ecotone_v1_normalization_proto_msgTypes,
	}.Build()
	File_ecotone_v1_normalization_proto = out.File
	file_ecotone_v1_normalization_proto_goTypes = nil
	file_ecotone_v1_normalization_proto_depIdxs = nil
}
