// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: ecotone/v1/normalization.proto

package ecotone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NormalizationService_Normalize_FullMethodName      = "/ecotone.v1.NormalizationService/Normalize"
	NormalizationService_NormalizeBatch_FullMethodName = "/ecotone.v1.NormalizationService/NormalizeBatch"
	NormalizationService_SplitSentences_FullMethodName = "/ecotone.v1.NormalizationService/SplitSentences"
	NormalizationService_ReloadGrammars_FullMethodName = "/ecotone.v1.NormalizationService/ReloadGrammars"
)

// NormalizationServiceClient is the client API for NormalizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NormalizationService provides text normalization and sentence segmentation
// for speech synthesis (TTS) and recognition (ASR) pipelines.
type NormalizationServiceClient interface {
	// Normalize transforms a single text utterance into its spoken form.
	Normalize(ctx context.Context, in *NormalizeRequest, opts ...grpc.CallOption) (*NormalizeResponse, error)
	// NormalizeBatch transforms multiple utterances in parallel.
	NormalizeBatch(ctx context.Context, in *NormalizeBatchRequest, opts ...grpc.CallOption) (*NormalizeBatchResponse, error)
	// SplitSentences segments text into individual sentences according to rules
	// and exception lexicons (e.g. not splitting on honorifics or abbreviations).
	SplitSentences(ctx context.Context, in *SplitSentencesRequest, opts ...grpc.CallOption) (*SplitSentencesResponse, error)
	// ReloadGrammars atomically hot-reloads normalizer grammars and configuration
	// without dropping in-flight requests.
	ReloadGrammars(ctx context.Context, in *ReloadGrammarsRequest, opts ...grpc.CallOption) (*ReloadGrammarsResponse, error)
}

type normalizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNormalizationServiceClient(cc grpc.ClientConnInterface) NormalizationServiceClient {
	return &normalizationServiceClient{cc}
}

func (c *normalizationServiceClient) Normalize(ctx context.Context, in *NormalizeRequest, opts ...grpc.CallOption) (*NormalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizeResponse)
	err := c.cc.Invoke(ctx, NormalizationService_Normalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalizationServiceClient) NormalizeBatch(ctx context.Context, in *NormalizeBatchRequest, opts ...grpc.CallOption) (*NormalizeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizeBatchResponse)
	err := c.cc.Invoke(ctx, NormalizationService_NormalizeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalizationServiceClient) SplitSentences(ctx context.Context, in *SplitSentencesRequest, opts ...grpc.CallOption) (*SplitSentencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitSentencesResponse)
	err := c.cc.Invoke(ctx, NormalizationService_SplitSentences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalizationServiceClient) ReloadGrammars(ctx context.Context, in *ReloadGrammarsRequest, opts ...grpc.CallOption) (*ReloadGrammarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadGrammarsResponse)
	err := c.cc.Invoke(ctx, NormalizationService_ReloadGrammars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NormalizationServiceServer is the server API for NormalizationService service.
// All implementations must embed UnimplementedNormalizationServiceServer
// for forward compatibility.
//
// NormalizationService provides text normalization and sentence segmentation
// for speech synthesis (TTS) and recognition (ASR) pipelines.
type NormalizationServiceServer interface {
	// Normalize transforms a single text utterance into its spoken form.
	Normalize(context.Context, *NormalizeRequest) (*NormalizeResponse, error)
	// NormalizeBatch transforms multiple utterances in parallel.
	NormalizeBatch(context.Context, *NormalizeBatchRequest) (*NormalizeBatchResponse, error)
	// SplitSentences segments text into individual sentences according to rules
	// and exception lexicons (e.g. not splitting on honorifics or abbreviations).
	SplitSentences(context.Context, *SplitSentencesRequest) (*SplitSentencesResponse, error)
	// ReloadGrammars atomically hot-reloads normalizer grammars and configuration
	// without dropping in-flight requests.
	ReloadGrammars(context.Context, *ReloadGrammarsRequest) (*ReloadGrammarsResponse, error)
	mustEmbedUnimplementedNormalizationServiceServer()
}

// UnimplementedNormalizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNormalizationServiceServer struct{}

func (UnimplementedNormalizationServiceServer) Normalize(context.Context, *NormalizeRequest) (*NormalizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Normalize not implemented")
}
func (UnimplementedNormalizationServiceServer) NormalizeBatch(context.Context, *NormalizeBatchRequest) (*NormalizeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NormalizeBatch not implemented")
}
func (UnimplementedNormalizationServiceServer) SplitSentences(context.Context, *SplitSentencesRequest) (*SplitSentencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SplitSentences not implemented")
}
func (UnimplementedNormalizationServiceServer) ReloadGrammars(context.Context, *ReloadGrammarsRequest) (*ReloadGrammarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadGrammars not implemented")
}
func (UnimplementedNormalizationServiceServer) mustEmbedUnimplementedNormalizationServiceServer() {}
func (UnimplementedNormalizationServiceServer) testEmbeddedByValue()                              {}

// UnsafeNormalizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NormalizationServiceServer will
// result in compilation errors.
type UnsafeNormalizationServiceServer interface {
	mustEmbedUnimplementedNormalizationServiceServer()
}

func RegisterNormalizationServiceServer(s grpc.ServiceRegistrar, srv NormalizationServiceServer) {
	// If the following call panics, it indicates UnimplementedNormalizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NormalizationService_ServiceDesc, srv)
}

func _NormalizationService_Normalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizationServiceServer).Normalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizationService_Normalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizationServiceServer).Normalize(ctx, req.(*NormalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalizationService_NormalizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizationServiceServer).NormalizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizationService_NormalizeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizationServiceServer).NormalizeBatch(ctx, req.(*NormalizeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalizationService_SplitSentences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitSentencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizationServiceServer).SplitSentences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizationService_SplitSentences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizationServiceServer).SplitSentences(ctx, req.(*SplitSentencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalizationService_ReloadGrammars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadGrammarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalizationServiceServer).ReloadGrammars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalizationService_ReloadGrammars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalizationServiceServer).ReloadGrammars(ctx, req.(*ReloadGrammarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NormalizationService_ServiceDesc is the grpc.ServiceDesc for NormalizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NormalizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecotone.v1.NormalizationService",
	HandlerType: (*NormalizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Normalize",
			Handler:    _NormalizationService_Normalize_Handler,
		},
		{
			MethodName: "NormalizeBatch",
			Handler:    _NormalizationService_NormalizeBatch_Handler,
		},
		{
			MethodName: "SplitSentences",
			Handler:    _NormalizationService_SplitSentences_Handler,
		},
		{
			MethodName: "ReloadGrammars",
			Handler:    _NormalizationService_ReloadGrammars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecotone/v1/normalization.proto",
}
