#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Comparison report skeleton from a matrix run with competitor targets -> <run_dir>/comparison.md

  scripts/compare/report.py benchmarks/runs/<date>-compare-<model>

Fills every measured table of the standard report (docs/operate/model-comparison.md, "Report template") from the
run's receipts and the competitor profiles, and leaves the narrative sections as TODO markers for the author.
Run `scripts/bench_matrix.py report <run_dir>` first (it writes summary.json).
"""
import argparse
import json
import os
import statistics
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from compare import exposure  # noqa: E402
from matrix import compare_cases  # noqa: E402
from matrix import metrics as M  # noqa: E402
from matrix import report as R  # noqa: E402
from matrix.targets import load_profile  # noqa: E402

SUITES = ("jev_systemone", "calib_systemone", "intents_systemone", "gate_mixed_noul", "gate_mixed_noul_single",
          "massive_spot", "massive", "xnli", "typed")
TODO = "_TODO (author):_"


def f(x, d=3):
    return R._f(x, d)


def build(run_dir):
    man, by = R.load_run(run_dir)
    with open(os.path.join(run_dir, "summary.json")) as fh:
        summ = json.load(fh)
    mx = man["matrix"]
    comps = [t for t in mx["targets"] if t.get("role") == "competitor"]
    if not comps:
        raise SystemExit("no competitor targets in this run (bench_matrix.py run ... --competitor name=url)")
    base = mx.get("baseline") or next(t["name"] for t in mx["targets"] if t.get("role") != "competitor")
    names = [base] + [t["name"] for t in comps]
    profiles = {t["name"]: (load_profile(t["profile"]) if t.get("profile") else {}) for t in comps}
    first = {s: {n: M.rows(lst[0][1]) for n, lst in by[s].items()} for s in SUITES if s in by}
    L = [f"# {', '.join(p.get('name', n) for n, p in profiles.items())} vs dgem: comparison report", "",
         f"- Run `{man['run_id']}`, matrix {mx['matrix_version']} tier {mx['tier']}, commit `{man.get('git_commit', '')[:10]}`.",
         f"- Evidence level: **E2** (lab head-to-head, same session){' + E3 (frozen sets)' if 'massive' in by else ''}.",
         f"- Generated by `scripts/compare/report.py`; tables are from receipts, narrative sections are marked {TODO}.", ""]

    # 1. bottom line
    L += ["## 1. Bottom line", "", f"{TODO} 4–6 numbered findings, each with n and a paired test. Lead with the in-domain vs "
          "out-of-domain split (section 3), then calibration, latency crossover, and any dgem defect found.", ""]

    # 2. what we compared
    L += ["## 2. What we compared", "", "| | " + " | ".join(names) + " |", "|---|" + "---|" * len(names)]
    rows2 = [("role", lambda n: "dgem (baseline)" if n == base else "competitor"),
             ("size class", lambda n: profiles.get(n, {}).get("identity", {}).get("size_class", "26B-A4B MoE (3.8B active), NVFP4" if n == base else "—")),
             ("architecture", lambda n: profiles.get(n, {}).get("identity", {}).get("architecture", "DiffusionGemma, zero-shot policy readout" if n == base else "—")),
             ("revision", lambda n: _rev(mx, n, profiles)),
             ("option limit", lambda n: "26 native, more via adapter" if n == base else str(profiles.get(n, {}).get("serving", {}).get("max_choice_options", "—"))),
             ("deterministic / concurrency-safe (profile)", lambda n: "no / yes" if n == base else
              f"{_yn(profiles.get(n, {}).get('serving', {}).get('deterministic'))} / {_yn(profiles.get(n, {}).get('serving', {}).get('concurrency_safe'))}")]
    for lab, fn in rows2:
        L.append(f"| {lab} | " + " | ".join(fn(n) for n in names) + " |")
    L += ["", f"{TODO} hardware for each target, preflight result (`scripts/compare/preflight.py`), any server change made "
          "to run the competitor safely, and how many runs per suite.", ""]

    # 3. accuracy
    L += ["## 3. Accuracy", "", "| suite | n | " + " | ".join(f"{n}: runs correct (mean acc)" for n in names) +
          " | paired run 1: only dgem / only competitor, McNemar p |", "|---|---|" + "---|" * len(names) + "---|"]
    for s in SUITES:
        if s not in by:
            continue
        cells, n_items = [], None
        for n in names:
            ss = summ["suites"].get(s, {}).get(n)
            if not ss:
                cells.append("—")
                continue
            n_items = ss["runs"][0]["n"]
            cells.append(f"{', '.join(str(r['correct']) for r in ss['runs'])} ({ss['accuracy']:.3f})")
        pair = []
        for c in comps:
            cs = (summ.get("competitors", {}).get(c["name"]) or {}).get(s)
            if cs:
                pair.append(f"{cs['only_ref']} / {cs['only_competitor']}, p={cs['mcnemar_p']:.2g}")
        L.append(f"| {s} | {n_items} | " + " | ".join(cells) + f" | {'; '.join(pair) or '—'} |")
    L.append("")
    for c in comps:
        prof = profiles[c["name"]]
        pooled = {n: [r for s in first for r in first[s].get(n, [])] for n in (base, c["name"])}
        sp = exposure.split(prof, pooled, c["name"])
        if sp:
            L += [f"### By training exposure of {c['name']} (first run, items both answered; source: {prof.get('exposure_source', '—')})", "",
                  f"| exposure | n | {base} | {c['name']} |", "|---|---|---|---|"]
            for t, n, acc in sp:
                L.append(f"| {t} | {n} | {acc[base]:.3f} | {acc[c['name']]:.3f} |")
            L.append("")
    L += [f"{TODO} where each side wins (families, languages), with counts.", ""]

    # 4. calibration
    L += ["## 4. Calibration", "", "First run of each suite. Held-out = 5-fold temperature fitted out of sample "
          "(the matrix's T-cal). ≥0.9 = share of answers at confidence ≥ 0.9 and their accuracy.", "",
          "| suite | target | ECE raw | ECE held-out | Brier | AUROC | ≥0.9 share / accuracy |", "|---|---|---|---|---|---|---|"]
    for s in first:
        for n in names:
            ss = summ["suites"].get(s, {}).get(n)
            rr = first[s].get(n)
            if not ss or not rr:
                continue
            ho = ss.get("heldout") or {}
            hi = [r for r in rr if r["confidence"] >= 0.9]
            L.append(f"| {s} | {n} | {f(ho.get('ece_raw'))} | {f(ho.get('ece_heldout'))} | {f(ss.get('brier'))} | "
                     f"{f(ss.get('auroc'))} | {len(hi) / len(rr):.2f} / {f(statistics.mean(r['accurate'] for r in hi) if hi else None)} |")
    if "gate_mixed_noul" in by:
        L += ["", "Cross-slot coupling on `gate_mixed_noul` (two yes/no answers with the same label; gold 7 of 51): " +
              "; ".join(f"{n} {', '.join(str(compare_cases.coupling(M.rows(r))['equal']) for _, r in lst)}"
                        for n, lst in by["gate_mixed_noul"].items())]
    L += ["", f"{TODO} how each fails out of domain (cautious vs overconfident) and what temperature dgem needs.", ""]

    # 5. latency and cost
    L += ["## 5. Latency and cost", ""]
    if "latency" in by:
        lat = {n: lst[0][1] for n, lst in by["latency"].items()}
        modes = sorted({m for d in lat.values() for m in d["modes"]})
        L += ["| mode | " + " | ".join(f"{n}: server p50 / wall p50 ms" for n in names if n in lat) + " |",
              "|---|" + "---|" * len([n for n in names if n in lat])]
        for m in modes:
            L.append(f"| {m} | " + " | ".join(f"{f(lat[n]['modes'].get(m, {}).get('server_p50'), 1)} / "
                                               f"{f(lat[n]['modes'].get(m, {}).get('wall_p50'), 1)}" for n in names if n in lat) + " |")
        sweeps = sorted({k for d in lat.values() for k in d["sweep"]})
        for k in sweeps:
            L.append(f"| sweep {k} req/s | " + " | ".join(f(lat[n]["sweep"].get(k, {}).get("rps"), 1) for n in names if n in lat) + " |")
        L.append("")
    L += [f"{TODO} latency vs input length and question count, cold start, cost per 1k decisions at saturation.", ""]

    # 6-9
    L += ["## 6. Caveats", "", f"{TODO} size class, hardware, server patches, suites we wrote ourselves, nondeterminism, "
          "post-hoc diagnostics labelled as such.", "",
          "## 7. Findings for dgem", "", "Every finding gets one type and one destination (docs/operate/model-comparison.md, \"Intake\").", "",
          "| # | finding | evidence | type | destination |", "|---|---|---|---|---|", f"| 1 | {TODO} | | bug / hypothesis / coverage / re-run / doc | issue / PROP-XX / matrix vN / run id / PR |", "",
          "## 8. Upstream feedback to the competitor", "", f"{TODO} defects found in their server or docs, offered as issues.", "",
          "## 9. Cloud resources", "", "| resource | status |", "|---|---|", f"| {TODO} | deleted / unchanged |", ""]
    return "\n".join(L) + "\n"


def _rev(mx, n, profiles):
    t = next(x for x in mx["targets"] if x["name"] == n)
    h = t.get("health") or {}
    if h.get("version"):
        return f"{h['version']} ({h.get('revision', '')})"
    w = profiles.get(n, {}).get("identity", {}).get("weights", {})
    return f"{w.get('revision', '—')[:10]}" if w else "—"


def _yn(v):
    return "—" if v is None else ("yes" if v else "no")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run_dir")
    a = ap.parse_args()
    md = build(os.path.abspath(a.run_dir))
    out = os.path.join(a.run_dir, "comparison.md")
    with open(out, "w") as fh:
        fh.write(md)
    print(out)


if __name__ == "__main__":
    main()
